name: Fetch News to Firebase

on:
  schedule:
    - cron: '*/5 * * * *' # Her 5 dakikada bir
  workflow_dispatch: # Manuel tetiklemeye izin verir

jobs:
  fetch-and-cache:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm install firebase-admin rss-parser cheerio
        
      - name: Run fetch scripts
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          node scripts/fetchNews.js
          node scripts/fetchAuthors.js
